### ISSUE TITLE
Hexen 2 mdl flags

### ISSUE THREAD

**Issue by Mathuz-z-z** [nzp-team/tools#1]
Hi, I started using your modified blender exporter as it greatly improved the issue with "dancing" vertices and allowed to create less "blocky" models. However, the models are made for Hexen 2, which uses many more model flags. While most of them are not really important, there are several flags providing transparency/translucency. Would it be possible to make these flags available? I have a complete list of these flags as I am not really sure whether they are documented somewhere. Thanks

**Comment by blubs** [comment]
Though I'm not the original author of the mod (I just modified it to give better vertex swimming control), I've reviewed how the exporter currently handles flags, and I don't think it'd be a huge lift to add in support for them. Would you mind sharing the list of flags that you'd be interested in using?

**Comment by Mathuz-z-z** [comment]
Here is the complete list:

EF_FIREBALL = 256
EF_ICE = 512
EF_MIP_MAP = 1024
EF_SPIT = 2048
**EF_TRANSPARENT = 4096**
EF_VERTICAL_SPRAY = 8192
**EF_HOLEY/FENCE_TRANSPARENT = 16384**
**EF_TRANSLUCENT = 32768**
**EF_ALWAYS_FACING = 65536**
EF_VORP_MISSILE = 131072
EF_SET_STAFF = 262144
EF_MAGICMISSILE = 524288
EF_BONESHARD = 1048576
EF_SCARAB = 2097152
EF_ACIDBALL = 4194304
EF_BLOODSHOT = 8388608
EF_MIP_MAP_FAR = 16777216

The ones in the bold text I'm interested in.

**Comment by blubs** [comment]
I've added a new "Flags" field to the exporter in this commit:
https://github.com/nzp-team/tools/commit/aefe4d56d5664db96d764cb6b2ddfcd9816e2e19

Specifying an integer value will directly insert those bitflags into the MDL (and ignore the "Effects" / "Rotate" value set by the exporter)

You should be able to directly set the flag value to your desired value with this. Give it a shot!

**Comment by Mathuz-z-z** [comment]
Ideal solution. Everything seems to be working. 

I appreciate your prompt reaction, you helped me a great deal!
